kind: ReplicationController
apiVersion: v1
metadata:
  name: webserver-rc
  labels:
    version: v1
    env: prod
    group: webserver
spec:
  replicas: 3
  selector:
    version: v1
    env: prod
    group: webserver
  template:
    metadata:
      generateName: webserver-pod-
      labels:
        version: v1
        env: prod
        group: webserver
    spec:
      containers:
        - name: webserver
          image: us.gcr.io/sortalonco/webserver
          command: [ "sortalonco" ]
          ports:
            - containerPort: 3000
